# Makefile.in generated by automake 1.14.1 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994-2013 Free Software Foundation, Inc.

# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.







am__is_gnu_make = test -n '$(MAKEFILE_LIST)' && test -n '$(MAKELEVEL)'
am__make_running_with_option = \
  case $${target_option-} in \
      ?) ;; \
      *) echo "am__make_running_with_option: internal error: invalid" \
              "target option '$${target_option-}' specified" >&2; \
         exit 1;; \
  esac; \
  has_opt=no; \
  sane_makeflags=$$MAKEFLAGS; \
  if $(am__is_gnu_make); then \
    sane_makeflags=$$MFLAGS; \
  else \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        bs=\\; \
        sane_makeflags=`printf '%s\n' "$$MAKEFLAGS" \
          | sed "s/$$bs$$bs[$$bs $$bs	]*//g"`;; \
    esac; \
  fi; \
  skip_next=no; \
  strip_trailopt () \
  { \
    flg=`printf '%s\n' "$$flg" | sed "s/$$1.*$$//"`; \
  }; \
  for flg in $$sane_makeflags; do \
    test $$skip_next = yes && { skip_next=no; continue; }; \
    case $$flg in \
      *=*|--*) continue;; \
        -*I) strip_trailopt 'I'; skip_next=yes;; \
      -*I?*) strip_trailopt 'I';; \
        -*O) strip_trailopt 'O'; skip_next=yes;; \
      -*O?*) strip_trailopt 'O';; \
        -*l) strip_trailopt 'l'; skip_next=yes;; \
      -*l?*) strip_trailopt 'l';; \
      -[dEDm]) skip_next=yes;; \
      -[JT]) skip_next=yes;; \
    esac; \
    case $$flg in \
      *$$target_option*) has_opt=yes; break;; \
    esac; \
  done; \
  test $$has_opt = yes
am__make_dryrun = (target_option=n; $(am__make_running_with_option))
am__make_keepgoing = (target_option=k; $(am__make_running_with_option))
pkgdatadir = $(datadir)/jel
pkgincludedir = $(includedir)/jel
pkglibdir = $(libdir)/jel
pkglibexecdir = $(libexecdir)/jel
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = x86_64-apple-darwin13.2.0
bin_PROGRAMS = jpegtran$(EXEEXT) wedge$(EXEEXT) unwedge$(EXEEXT) \
	jblock$(EXEEXT) jhist$(EXEEXT) jquant$(EXEEXT) wcap$(EXEEXT)
subdir = .
DIST_COMMON = $(srcdir)/Makefile.in $(srcdir)/Makefile.am \
	$(top_srcdir)/configure $(am__configure_deps) \
	$(srcdir)/jel.pc.in $(top_srcdir)/config-aux/depcomp \
	$(nobase_include_HEADERS) README config-aux/compile \
	config-aux/config.guess config-aux/config.sub \
	config-aux/depcomp config-aux/install-sh config-aux/missing \
	$(top_srcdir)/config-aux/compile \
	$(top_srcdir)/config-aux/config.guess \
	$(top_srcdir)/config-aux/config.sub \
	$(top_srcdir)/config-aux/install-sh \
	$(top_srcdir)/config-aux/missing
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_CLEAN_FILES = jel.pc
CONFIG_CLEAN_VPATH_FILES =
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = f=`echo $$p | sed -e 's|^.*/||'`;
am__install_max = 40
am__nobase_strip_setup = \
  srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*|]/\\\\&/g'`
am__nobase_strip = \
  for p in $$list; do echo "$$p"; done | sed -e "s|$$srcdirstrip/||"
am__nobase_list = $(am__nobase_strip_setup); \
  for p in $$list; do echo "$$p $$p"; done | \
  sed "s| $$srcdirstrip/| |;"' / .*\//!s/ .*/ ./; s,\( .*\)/[^/]*$$,\1,' | \
  $(AWK) 'BEGIN { files["."] = "" } { files[$$2] = files[$$2] " " $$1; \
    if (++n[$$2] == $(am__install_max)) \
      { print $$2, files[$$2]; n[$$2] = 0; files[$$2] = "" } } \
    END { for (dir in files) print dir, files[dir] }'
am__base_list = \
  sed '$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;s/\n/ /g' | \
  sed '$$!N;$$!N;$$!N;$$!N;s/\n/ /g'
am__uninstall_files_from_dir = { \
  test -z "$$files" \
    || { test ! -d "$$dir" && test ! -f "$$dir" && test ! -r "$$dir"; } \
    || { echo " ( cd '$$dir' && rm -f" $$files ")"; \
         $(am__cd) "$$dir" && rm -f $$files; }; \
  }
am__installdirs = "$(DESTDIR)$(jeldir)" "$(DESTDIR)$(bindir)" \
	"$(DESTDIR)$(pkgconfigdir)" "$(DESTDIR)$(includedir)"
LIBRARIES = $(jel_LIBRARIES) $(noinst_LIBRARIES)
AR = ar
ARFLAGS = cru
AM_V_AR = $(am__v_AR_$(V))
am__v_AR_ = $(am__v_AR_$(AM_DEFAULT_VERBOSITY))
am__v_AR_0 = @echo "  AR      " $@;
am__v_AR_1 = 
libjel_a_AR = $(AR) $(ARFLAGS)
libjel_a_LIBADD =
am__dirstamp = $(am__leading_dot)dirstamp
am__objects_1 = jpeg-6b/jmemansi.$(OBJEXT) jpeg-6b/jdatadst.$(OBJEXT)
am__objects_2 = rscode/rs.$(OBJEXT) rscode/galois.$(OBJEXT) \
	rscode/berlekamp.$(OBJEXT) rscode/crcgen.$(OBJEXT)
am__objects_3 = jpeg-6b/jcapimin.$(OBJEXT) jpeg-6b/jcapistd.$(OBJEXT) \
	jpeg-6b/jccoefct.$(OBJEXT) jpeg-6b/jccolor.$(OBJEXT) \
	jpeg-6b/jcdctmgr.$(OBJEXT) jpeg-6b/jchuff.$(OBJEXT) \
	jpeg-6b/jcinit.$(OBJEXT) jpeg-6b/jcmainct.$(OBJEXT) \
	jpeg-6b/jcmarker.$(OBJEXT) jpeg-6b/jcmaster.$(OBJEXT) \
	jpeg-6b/jcomapi.$(OBJEXT) jpeg-6b/jcparam.$(OBJEXT) \
	jpeg-6b/jcphuff.$(OBJEXT) jpeg-6b/jcprepct.$(OBJEXT) \
	jpeg-6b/jcsample.$(OBJEXT) jpeg-6b/jctrans.$(OBJEXT) \
	jpeg-6b/jdapimin.$(OBJEXT) jpeg-6b/jdapistd.$(OBJEXT) \
	jpeg-6b/jdatadst.$(OBJEXT) jpeg-6b/jdatasrc.$(OBJEXT) \
	jpeg-6b/jdcoefct.$(OBJEXT) jpeg-6b/jdcolor.$(OBJEXT) \
	jpeg-6b/jddctmgr.$(OBJEXT) jpeg-6b/jdhuff.$(OBJEXT) \
	jpeg-6b/jdinput.$(OBJEXT) jpeg-6b/jdmainct.$(OBJEXT) \
	jpeg-6b/jdmarker.$(OBJEXT) jpeg-6b/jdmaster.$(OBJEXT) \
	jpeg-6b/jdmerge.$(OBJEXT) jpeg-6b/jdphuff.$(OBJEXT) \
	jpeg-6b/jdpostct.$(OBJEXT) jpeg-6b/jdsample.$(OBJEXT) \
	jpeg-6b/jdtrans.$(OBJEXT) jpeg-6b/jerror.$(OBJEXT) \
	jpeg-6b/jfdctflt.$(OBJEXT) jpeg-6b/jfdctfst.$(OBJEXT) \
	jpeg-6b/jfdctint.$(OBJEXT) jpeg-6b/jidctflt.$(OBJEXT) \
	jpeg-6b/jidctfst.$(OBJEXT) jpeg-6b/jidctint.$(OBJEXT) \
	jpeg-6b/jidctred.$(OBJEXT) jpeg-6b/jquant1.$(OBJEXT) \
	jpeg-6b/jquant2.$(OBJEXT) jpeg-6b/jutils.$(OBJEXT) \
	jpeg-6b/jmemmgr.$(OBJEXT)
am_libjel_a_OBJECTS = libjel/ijel-ecc.$(OBJEXT) libjel/ijel.$(OBJEXT) \
	libjel/jpeg-fd-dst.$(OBJEXT) libjel/jpeg-fd-src.$(OBJEXT) \
	libjel/jpeg-mem-dst.$(OBJEXT) libjel/jpeg-mem-src.$(OBJEXT) \
	libjel/jel.$(OBJEXT) $(am__objects_1) $(am__objects_2) \
	$(am__objects_3)
libjel_a_OBJECTS = $(am_libjel_a_OBJECTS)
libjpeg_a_AR = $(AR) $(ARFLAGS)
libjpeg_a_LIBADD =
am_libjpeg_a_OBJECTS = jpeg-6b/jcapimin.$(OBJEXT) \
	jpeg-6b/jcapistd.$(OBJEXT) jpeg-6b/jccoefct.$(OBJEXT) \
	jpeg-6b/jccolor.$(OBJEXT) jpeg-6b/jcdctmgr.$(OBJEXT) \
	jpeg-6b/jchuff.$(OBJEXT) jpeg-6b/jcinit.$(OBJEXT) \
	jpeg-6b/jcmainct.$(OBJEXT) jpeg-6b/jcmarker.$(OBJEXT) \
	jpeg-6b/jcmaster.$(OBJEXT) jpeg-6b/jcomapi.$(OBJEXT) \
	jpeg-6b/jcparam.$(OBJEXT) jpeg-6b/jcphuff.$(OBJEXT) \
	jpeg-6b/jcprepct.$(OBJEXT) jpeg-6b/jcsample.$(OBJEXT) \
	jpeg-6b/jctrans.$(OBJEXT) jpeg-6b/jdapimin.$(OBJEXT) \
	jpeg-6b/jdapistd.$(OBJEXT) jpeg-6b/jdatadst.$(OBJEXT) \
	jpeg-6b/jdatasrc.$(OBJEXT) jpeg-6b/jdcoefct.$(OBJEXT) \
	jpeg-6b/jdcolor.$(OBJEXT) jpeg-6b/jddctmgr.$(OBJEXT) \
	jpeg-6b/jdhuff.$(OBJEXT) jpeg-6b/jdinput.$(OBJEXT) \
	jpeg-6b/jdmainct.$(OBJEXT) jpeg-6b/jdmarker.$(OBJEXT) \
	jpeg-6b/jdmaster.$(OBJEXT) jpeg-6b/jdmerge.$(OBJEXT) \
	jpeg-6b/jdphuff.$(OBJEXT) jpeg-6b/jdpostct.$(OBJEXT) \
	jpeg-6b/jdsample.$(OBJEXT) jpeg-6b/jdtrans.$(OBJEXT) \
	jpeg-6b/jerror.$(OBJEXT) jpeg-6b/jfdctflt.$(OBJEXT) \
	jpeg-6b/jfdctfst.$(OBJEXT) jpeg-6b/jfdctint.$(OBJEXT) \
	jpeg-6b/jidctflt.$(OBJEXT) jpeg-6b/jidctfst.$(OBJEXT) \
	jpeg-6b/jidctint.$(OBJEXT) jpeg-6b/jidctred.$(OBJEXT) \
	jpeg-6b/jquant1.$(OBJEXT) jpeg-6b/jquant2.$(OBJEXT) \
	jpeg-6b/jutils.$(OBJEXT) jpeg-6b/jmemmgr.$(OBJEXT)
libjpeg_a_OBJECTS = $(am_libjpeg_a_OBJECTS)
PROGRAMS = $(bin_PROGRAMS)
am_jblock_OBJECTS = utils/jblock.$(OBJEXT) $(am__objects_1)
jblock_OBJECTS = $(am_jblock_OBJECTS)
jblock_DEPENDENCIES = $(JEL_LIBS)
am_jhist_OBJECTS = utils/jhist.$(OBJEXT) $(am__objects_1)
jhist_OBJECTS = $(am_jhist_OBJECTS)
jhist_DEPENDENCIES = $(JEL_LIBS)
am_jpegtran_OBJECTS = jpeg-6b/jpegtran.$(OBJEXT) \
	jpeg-6b/transupp.$(OBJEXT) jpeg-6b/cdjpeg.$(OBJEXT) \
	jpeg-6b/rdswitch.$(OBJEXT) $(am__objects_1)
jpegtran_OBJECTS = $(am_jpegtran_OBJECTS)
jpegtran_DEPENDENCIES = libjpeg.a
am_jquant_OBJECTS = utils/jquant.$(OBJEXT) $(am__objects_1)
jquant_OBJECTS = $(am_jquant_OBJECTS)
jquant_DEPENDENCIES = $(JEL_LIBS)
am_unwedge_OBJECTS = utils/unwedge.$(OBJEXT) $(am__objects_1)
unwedge_OBJECTS = $(am_unwedge_OBJECTS)
unwedge_DEPENDENCIES = $(JEL_LIBS)
am_wcap_OBJECTS = utils/wcap.$(OBJEXT) $(am__objects_1)
wcap_OBJECTS = $(am_wcap_OBJECTS)
wcap_DEPENDENCIES = $(JEL_LIBS)
am_wedge_OBJECTS = utils/wedge.$(OBJEXT) $(am__objects_1)
wedge_OBJECTS = $(am_wedge_OBJECTS)
wedge_DEPENDENCIES = $(JEL_LIBS)
AM_V_P = $(am__v_P_$(V))
am__v_P_ = $(am__v_P_$(AM_DEFAULT_VERBOSITY))
am__v_P_0 = false
am__v_P_1 = :
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN     " $@;
am__v_GEN_1 = 
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
am__v_at_1 = 
DEFAULT_INCLUDES = 
depcomp = $(SHELL) $(top_srcdir)/config-aux/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
AM_V_CC = $(am__v_CC_$(V))
am__v_CC_ = $(am__v_CC_$(AM_DEFAULT_VERBOSITY))
am__v_CC_0 = @echo "  CC      " $@;
am__v_CC_1 = 
CCLD = $(CC)
LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_CCLD = $(am__v_CCLD_$(V))
am__v_CCLD_ = $(am__v_CCLD_$(AM_DEFAULT_VERBOSITY))
am__v_CCLD_0 = @echo "  CCLD    " $@;
am__v_CCLD_1 = 
SOURCES = $(libjel_a_SOURCES) $(libjpeg_a_SOURCES) $(jblock_SOURCES) \
	$(jhist_SOURCES) $(jpegtran_SOURCES) $(jquant_SOURCES) \
	$(unwedge_SOURCES) $(wcap_SOURCES) $(wedge_SOURCES)
DIST_SOURCES = $(libjel_a_SOURCES) $(libjpeg_a_SOURCES) \
	$(jblock_SOURCES) $(jhist_SOURCES) $(jpegtran_SOURCES) \
	$(jquant_SOURCES) $(unwedge_SOURCES) $(wcap_SOURCES) \
	$(wedge_SOURCES)
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
DATA = $(pkgconfig_DATA)
HEADERS = $(nobase_include_HEADERS)
am__tagged_files = $(HEADERS) $(SOURCES) $(TAGS_FILES) $(LISP)
# Read a list of newline-separated strings from the standard input,
# and print each of them once, without duplicates.  Input order is
# *not* preserved.
am__uniquify_input = $(AWK) '\
  BEGIN { nonempty = 0; } \
  { items[$$0] = 1; nonempty = 1; } \
  END { if (nonempty) { for (i in items) print i; }; } \
'
# Make sure the list of sources is unique.  This is necessary because,
# e.g., the same source file might be shared among _SOURCES variables
# for different programs/libraries.
am__define_uniq_tagged_files = \
  list='$(am__tagged_files)'; \
  unique=`for i in $$list; do \
    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
  done | $(am__uniquify_input)`
ETAGS = etags
CTAGS = ctags
CSCOPE = cscope
AM_RECURSIVE_TARGETS = cscope
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  if test -d "$(distdir)"; then \
    find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
      && rm -rf "$(distdir)" \
      || { sleep 5 && rm -rf "$(distdir)"; }; \
  else :; fi
am__post_remove_distdir = $(am__remove_distdir)
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
DIST_TARGETS = dist-gzip
distuninstallcheck_listfiles = find . -type f -print
am__distuninstallcheck_listfiles = $(distuninstallcheck_listfiles) \
  | sed 's|^\./|$(prefix)/|' | grep -v '$(infodir)/dir$$'
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /Users/connolly/Desktop/Projects/Current/SAFER/src/jel/config-aux/missing aclocal-1.14
AMTAR = $${TAR-tar}
AM_DEFAULT_VERBOSITY = 1
AUTOCONF = ${SHELL} /Users/connolly/Desktop/Projects/Current/SAFER/src/jel/config-aux/missing autoconf
AUTOHEADER = ${SHELL} /Users/connolly/Desktop/Projects/Current/SAFER/src/jel/config-aux/missing autoheader
AUTOMAKE = ${SHELL} /Users/connolly/Desktop/Projects/Current/SAFER/src/jel/config-aux/missing automake-1.14
AWK = awk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2
CPPFLAGS = 
CYGPATH_W = echo
DEFS = -DPACKAGE_NAME=\"jel\" -DPACKAGE_TARNAME=\"jel\" -DPACKAGE_VERSION=\"1.0\" -DPACKAGE_STRING=\"jel\ 1.0\" -DPACKAGE_BUGREPORT=\"iam@csl.sri.com\" -DPACKAGE_URL=\"\" -DPACKAGE=\"jel\" -DVERSION=\"1.0\"
DEPDIR = .deps
ECHO_C = \c
ECHO_N = 
ECHO_T = 
EXEEXT = 
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LDFLAGS = 
LIBOBJS = 
LIBS = 
LTLIBOBJS = 
MAKEINFO = ${SHELL} /Users/connolly/Desktop/Projects/Current/SAFER/src/jel/config-aux/missing makeinfo
MKDIR_P = config-aux/install-sh -c -d
OBJEXT = o
PACKAGE = jel
PACKAGE_BUGREPORT = iam@csl.sri.com
PACKAGE_NAME = jel
PACKAGE_STRING = jel 1.0
PACKAGE_TARNAME = jel
PACKAGE_URL = 
PACKAGE_VERSION = 1.0
PATH_SEPARATOR = :
RANLIB = ranlib
SET_MAKE = 
SHELL = /bin/sh
STRIP = 
VERSION = 1.0
abs_builddir = /Users/connolly/Desktop/Projects/Current/SAFER/src/jel
abs_srcdir = /Users/connolly/Desktop/Projects/Current/SAFER/src/jel
abs_top_builddir = /Users/connolly/Desktop/Projects/Current/SAFER/src/jel
abs_top_srcdir = /Users/connolly/Desktop/Projects/Current/SAFER/src/jel
ac_ct_CC = gcc
am__include = include
am__leading_dot = .
am__quote = 
am__tar = $${TAR-tar} chof - "$$tardir"
am__untar = $${TAR-tar} xf -
bindir = $(exec_prefix)/bin
build = x86_64-apple-darwin13.2.0
build_alias = 
build_cpu = x86_64
build_os = darwin13.2.0
build_vendor = apple
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host_alias = 
htmldir = ${docdir}
includedir = $(prefix)
infodir = ${datarootdir}/info
install_sh = ${SHELL} /Users/connolly/Desktop/Projects/Current/SAFER/src/jel/config-aux/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = $(MKDIR_P)
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
PROJECT_GIT_ORIG := $(shell git config --get remote.origin.url 2>/dev/null || echo "unknownGITorigin")
PROJECT_GIT_BRCH := $(shell git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknownGITbranch")
PROJECT_GIT_HASH := $(shell git log --pretty=format:'%H' -n 1 2>/dev/null || echo "unknownGIThash")
PROJECT_GIT_TIME := $(shell git log --pretty=format:'%ci' -n 1 2>/dev/null || echo "unknownGITtime")
PROJECT_GIT_STAMPS = \
	-DPROJECT_GIT_ORIG='"$(PROJECT_GIT_ORIG)"' \
	-DPROJECT_GIT_BRCH='"$(PROJECT_GIT_BRCH)"' \
	-DPROJECT_GIT_HASH='"$(PROJECT_GIT_HASH)"' \
	-DPROJECT_GIT_TIME='"$(PROJECT_GIT_TIME)"'

ACLOCAL_AMFLAGS = -I config-aux --install
AM_CPPFLAGS = -Werror -Wall -DECC -DJEL_VERSION='"$(VERSION)"' -I. -I$(srcdir)/include -I$(srcdir)/rscode  $(PROJECT_GIT_STAMPS)
noinst_LIBRARIES = libjpeg.a
jeldir = $(prefix)/lib
jel_LIBRARIES = libjel.a
SYSDEPSOURCES = \
	jpeg-6b/jmemansi.c \
	jpeg-6b/jdatadst.c 

pkgconfigdir = $(prefix)/lib/pkgconfig
pkgconfig_DATA = jel.pc
nobase_include_HEADERS = \
	include/jel/jel.h \
	include/jel/jpeg-6b/jconfig.h \
	include/jel/jpeg-6b/jerror.h \
	include/jel/jpeg-6b/jinclude.h \
	include/jel/jpeg-6b/jmorecfg.h \
	include/jel/jpeg-6b/jpegint.h \
	include/jel/jpeg-6b/jpeglib.h

JEL_LIBS = $(jel_LIBRARIES)
wedge_SOURCES = utils/wedge.c $(SYSDEPSOURCES)
wedge_LDADD = $(JEL_LIBS)
unwedge_SOURCES = utils/unwedge.c $(SYSDEPSOURCES)
unwedge_LDADD = $(JEL_LIBS)
jblock_SOURCES = utils/jblock.c $(SYSDEPSOURCES)
jblock_LDADD = $(JEL_LIBS)
jhist_SOURCES = utils/jhist.c $(SYSDEPSOURCES)
jhist_LDADD = $(JEL_LIBS)
jquant_SOURCES = utils/jquant.c $(SYSDEPSOURCES)
jquant_LDADD = $(JEL_LIBS)
wcap_SOURCES = utils/wcap.c $(SYSDEPSOURCES)
wcap_LDADD = $(JEL_LIBS)
jpegtran_SOURCES = \
	jpeg-6b/jpegtran.c \
	jpeg-6b/transupp.c \
	jpeg-6b/cdjpeg.c \
	jpeg-6b/rdswitch.c \
	$(SYSDEPSOURCES)

jpegtran_LDADD = libjpeg.a
libjpeg_a_SOURCES = \
	jpeg-6b/jcapimin.c \
	jpeg-6b/jcapistd.c \
	jpeg-6b/jccoefct.c \
	jpeg-6b/jccolor.c \
	jpeg-6b/jcdctmgr.c \
	jpeg-6b/jchuff.c \
	jpeg-6b/jcinit.c \
	jpeg-6b/jcmainct.c \
	jpeg-6b/jcmarker.c \
	jpeg-6b/jcmaster.c \
	jpeg-6b/jcomapi.c \
	jpeg-6b/jcparam.c \
	jpeg-6b/jcphuff.c \
	jpeg-6b/jcprepct.c \
	jpeg-6b/jcsample.c \
	jpeg-6b/jctrans.c \
	jpeg-6b/jdapimin.c \
	jpeg-6b/jdapistd.c \
	jpeg-6b/jdatadst.c \
	jpeg-6b/jdatasrc.c \
	jpeg-6b/jdcoefct.c \
	jpeg-6b/jdcolor.c \
	jpeg-6b/jddctmgr.c \
	jpeg-6b/jdhuff.c \
  jpeg-6b/jdinput.c \
	jpeg-6b/jdmainct.c \
	jpeg-6b/jdmarker.c \
	jpeg-6b/jdmaster.c \
	jpeg-6b/jdmerge.c \
	jpeg-6b/jdphuff.c \
	jpeg-6b/jdpostct.c \
	jpeg-6b/jdsample.c \
	jpeg-6b/jdtrans.c \
	jpeg-6b/jerror.c \
	jpeg-6b/jfdctflt.c \
	jpeg-6b/jfdctfst.c \
	jpeg-6b/jfdctint.c \
	jpeg-6b/jidctflt.c \
	jpeg-6b/jidctfst.c \
	jpeg-6b/jidctint.c \
	jpeg-6b/jidctred.c \
	jpeg-6b/jquant1.c \
	jpeg-6b/jquant2.c \
	jpeg-6b/jutils.c \
	jpeg-6b/jmemmgr.c

RSCODE_SOURCES = \
	rscode/rs.c  \
	rscode/galois.c  \
	rscode/berlekamp.c  \
	rscode/crcgen.c

libjel_a_SOURCES = \
	libjel/ijel-ecc.c \
	libjel/ijel.c \
	libjel/jpeg-fd-dst.c \
	libjel/jpeg-fd-src.c \
	libjel/jpeg-mem-dst.c \
	libjel/jpeg-mem-src.c \
	libjel/jel.c \
	$(SYSDEPSOURCES) \
	$(RSCODE_SOURCES) \
	$(libjpeg_a_SOURCES) 

all: all-am

.SUFFIXES:
.SUFFIXES: .c .o .obj
am--refresh: Makefile
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --foreign'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --foreign \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):
jel.pc: $(top_builddir)/config.status $(srcdir)/jel.pc.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
install-jelLIBRARIES: $(jel_LIBRARIES)
	@$(NORMAL_INSTALL)
	@list='$(jel_LIBRARIES)'; test -n "$(jeldir)" || list=; \
	list2=; for p in $$list; do \
	  if test -f $$p; then \
	    list2="$$list2 $$p"; \
	  else :; fi; \
	done; \
	test -z "$$list2" || { \
	  echo " $(MKDIR_P) '$(DESTDIR)$(jeldir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(jeldir)" || exit 1; \
	  echo " $(INSTALL_DATA) $$list2 '$(DESTDIR)$(jeldir)'"; \
	  $(INSTALL_DATA) $$list2 "$(DESTDIR)$(jeldir)" || exit $$?; }
	@$(POST_INSTALL)
	@list='$(jel_LIBRARIES)'; test -n "$(jeldir)" || list=; \
	for p in $$list; do \
	  if test -f $$p; then \
	    $(am__strip_dir) \
	    echo " ( cd '$(DESTDIR)$(jeldir)' && $(RANLIB) $$f )"; \
	    ( cd "$(DESTDIR)$(jeldir)" && $(RANLIB) $$f ) || exit $$?; \
	  else :; fi; \
	done

uninstall-jelLIBRARIES:
	@$(NORMAL_UNINSTALL)
	@list='$(jel_LIBRARIES)'; test -n "$(jeldir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	dir='$(DESTDIR)$(jeldir)'; $(am__uninstall_files_from_dir)

clean-jelLIBRARIES:
	-test -z "$(jel_LIBRARIES)" || rm -f $(jel_LIBRARIES)

clean-noinstLIBRARIES:
	-test -z "$(noinst_LIBRARIES)" || rm -f $(noinst_LIBRARIES)
libjel/$(am__dirstamp):
	@$(MKDIR_P) libjel
	@: > libjel/$(am__dirstamp)
libjel/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) libjel/$(DEPDIR)
	@: > libjel/$(DEPDIR)/$(am__dirstamp)
libjel/ijel-ecc.$(OBJEXT): libjel/$(am__dirstamp) \
	libjel/$(DEPDIR)/$(am__dirstamp)
libjel/ijel.$(OBJEXT): libjel/$(am__dirstamp) \
	libjel/$(DEPDIR)/$(am__dirstamp)
libjel/jpeg-fd-dst.$(OBJEXT): libjel/$(am__dirstamp) \
	libjel/$(DEPDIR)/$(am__dirstamp)
libjel/jpeg-fd-src.$(OBJEXT): libjel/$(am__dirstamp) \
	libjel/$(DEPDIR)/$(am__dirstamp)
libjel/jpeg-mem-dst.$(OBJEXT): libjel/$(am__dirstamp) \
	libjel/$(DEPDIR)/$(am__dirstamp)
libjel/jpeg-mem-src.$(OBJEXT): libjel/$(am__dirstamp) \
	libjel/$(DEPDIR)/$(am__dirstamp)
libjel/jel.$(OBJEXT): libjel/$(am__dirstamp) \
	libjel/$(DEPDIR)/$(am__dirstamp)
jpeg-6b/$(am__dirstamp):
	@$(MKDIR_P) jpeg-6b
	@: > jpeg-6b/$(am__dirstamp)
jpeg-6b/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) jpeg-6b/$(DEPDIR)
	@: > jpeg-6b/$(DEPDIR)/$(am__dirstamp)
jpeg-6b/jmemansi.$(OBJEXT): jpeg-6b/$(am__dirstamp) \
	jpeg-6b/$(DEPDIR)/$(am__dirstamp)
jpeg-6b/jdatadst.$(OBJEXT): jpeg-6b/$(am__dirstamp) \
	jpeg-6b/$(DEPDIR)/$(am__dirstamp)
rscode/$(am__dirstamp):
	@$(MKDIR_P) rscode
	@: > rscode/$(am__dirstamp)
rscode/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) rscode/$(DEPDIR)
	@: > rscode/$(DEPDIR)/$(am__dirstamp)
rscode/rs.$(OBJEXT): rscode/$(am__dirstamp) \
	rscode/$(DEPDIR)/$(am__dirstamp)
rscode/galois.$(OBJEXT): rscode/$(am__dirstamp) \
	rscode/$(DEPDIR)/$(am__dirstamp)
rscode/berlekamp.$(OBJEXT): rscode/$(am__dirstamp) \
	rscode/$(DEPDIR)/$(am__dirstamp)
rscode/crcgen.$(OBJEXT): rscode/$(am__dirstamp) \
	rscode/$(DEPDIR)/$(am__dirstamp)
jpeg-6b/jcapimin.$(OBJEXT): jpeg-6b/$(am__dirstamp) \
	jpeg-6b/$(DEPDIR)/$(am__dirstamp)
jpeg-6b/jcapistd.$(OBJEXT): jpeg-6b/$(am__dirstamp) \
	jpeg-6b/$(DEPDIR)/$(am__dirstamp)
jpeg-6b/jccoefct.$(OBJEXT): jpeg-6b/$(am__dirstamp) \
	jpeg-6b/$(DEPDIR)/$(am__dirstamp)
jpeg-6b/jccolor.$(OBJEXT): jpeg-6b/$(am__dirstamp) \
	jpeg-6b/$(DEPDIR)/$(am__dirstamp)
jpeg-6b/jcdctmgr.$(OBJEXT): jpeg-6b/$(am__dirstamp) \
	jpeg-6b/$(DEPDIR)/$(am__dirstamp)
jpeg-6b/jchuff.$(OBJEXT): jpeg-6b/$(am__dirstamp) \
	jpeg-6b/$(DEPDIR)/$(am__dirstamp)
jpeg-6b/jcinit.$(OBJEXT): jpeg-6b/$(am__dirstamp) \
	jpeg-6b/$(DEPDIR)/$(am__dirstamp)
jpeg-6b/jcmainct.$(OBJEXT): jpeg-6b/$(am__dirstamp) \
	jpeg-6b/$(DEPDIR)/$(am__dirstamp)
jpeg-6b/jcmarker.$(OBJEXT): jpeg-6b/$(am__dirstamp) \
	jpeg-6b/$(DEPDIR)/$(am__dirstamp)
jpeg-6b/jcmaster.$(OBJEXT): jpeg-6b/$(am__dirstamp) \
	jpeg-6b/$(DEPDIR)/$(am__dirstamp)
jpeg-6b/jcomapi.$(OBJEXT): jpeg-6b/$(am__dirstamp) \
	jpeg-6b/$(DEPDIR)/$(am__dirstamp)
jpeg-6b/jcparam.$(OBJEXT): jpeg-6b/$(am__dirstamp) \
	jpeg-6b/$(DEPDIR)/$(am__dirstamp)
jpeg-6b/jcphuff.$(OBJEXT): jpeg-6b/$(am__dirstamp) \
	jpeg-6b/$(DEPDIR)/$(am__dirstamp)
jpeg-6b/jcprepct.$(OBJEXT): jpeg-6b/$(am__dirstamp) \
	jpeg-6b/$(DEPDIR)/$(am__dirstamp)
jpeg-6b/jcsample.$(OBJEXT): jpeg-6b/$(am__dirstamp) \
	jpeg-6b/$(DEPDIR)/$(am__dirstamp)
jpeg-6b/jctrans.$(OBJEXT): jpeg-6b/$(am__dirstamp) \
	jpeg-6b/$(DEPDIR)/$(am__dirstamp)
jpeg-6b/jdapimin.$(OBJEXT): jpeg-6b/$(am__dirstamp) \
	jpeg-6b/$(DEPDIR)/$(am__dirstamp)
jpeg-6b/jdapistd.$(OBJEXT): jpeg-6b/$(am__dirstamp) \
	jpeg-6b/$(DEPDIR)/$(am__dirstamp)
jpeg-6b/jdatasrc.$(OBJEXT): jpeg-6b/$(am__dirstamp) \
	jpeg-6b/$(DEPDIR)/$(am__dirstamp)
jpeg-6b/jdcoefct.$(OBJEXT): jpeg-6b/$(am__dirstamp) \
	jpeg-6b/$(DEPDIR)/$(am__dirstamp)
jpeg-6b/jdcolor.$(OBJEXT): jpeg-6b/$(am__dirstamp) \
	jpeg-6b/$(DEPDIR)/$(am__dirstamp)
jpeg-6b/jddctmgr.$(OBJEXT): jpeg-6b/$(am__dirstamp) \
	jpeg-6b/$(DEPDIR)/$(am__dirstamp)
jpeg-6b/jdhuff.$(OBJEXT): jpeg-6b/$(am__dirstamp) \
	jpeg-6b/$(DEPDIR)/$(am__dirstamp)
jpeg-6b/jdinput.$(OBJEXT): jpeg-6b/$(am__dirstamp) \
	jpeg-6b/$(DEPDIR)/$(am__dirstamp)
jpeg-6b/jdmainct.$(OBJEXT): jpeg-6b/$(am__dirstamp) \
	jpeg-6b/$(DEPDIR)/$(am__dirstamp)
jpeg-6b/jdmarker.$(OBJEXT): jpeg-6b/$(am__dirstamp) \
	jpeg-6b/$(DEPDIR)/$(am__dirstamp)
jpeg-6b/jdmaster.$(OBJEXT): jpeg-6b/$(am__dirstamp) \
	jpeg-6b/$(DEPDIR)/$(am__dirstamp)
jpeg-6b/jdmerge.$(OBJEXT): jpeg-6b/$(am__dirstamp) \
	jpeg-6b/$(DEPDIR)/$(am__dirstamp)
jpeg-6b/jdphuff.$(OBJEXT): jpeg-6b/$(am__dirstamp) \
	jpeg-6b/$(DEPDIR)/$(am__dirstamp)
jpeg-6b/jdpostct.$(OBJEXT): jpeg-6b/$(am__dirstamp) \
	jpeg-6b/$(DEPDIR)/$(am__dirstamp)
jpeg-6b/jdsample.$(OBJEXT): jpeg-6b/$(am__dirstamp) \
	jpeg-6b/$(DEPDIR)/$(am__dirstamp)
jpeg-6b/jdtrans.$(OBJEXT): jpeg-6b/$(am__dirstamp) \
	jpeg-6b/$(DEPDIR)/$(am__dirstamp)
jpeg-6b/jerror.$(OBJEXT): jpeg-6b/$(am__dirstamp) \
	jpeg-6b/$(DEPDIR)/$(am__dirstamp)
jpeg-6b/jfdctflt.$(OBJEXT): jpeg-6b/$(am__dirstamp) \
	jpeg-6b/$(DEPDIR)/$(am__dirstamp)
jpeg-6b/jfdctfst.$(OBJEXT): jpeg-6b/$(am__dirstamp) \
	jpeg-6b/$(DEPDIR)/$(am__dirstamp)
jpeg-6b/jfdctint.$(OBJEXT): jpeg-6b/$(am__dirstamp) \
	jpeg-6b/$(DEPDIR)/$(am__dirstamp)
jpeg-6b/jidctflt.$(OBJEXT): jpeg-6b/$(am__dirstamp) \
	jpeg-6b/$(DEPDIR)/$(am__dirstamp)
jpeg-6b/jidctfst.$(OBJEXT): jpeg-6b/$(am__dirstamp) \
	jpeg-6b/$(DEPDIR)/$(am__dirstamp)
jpeg-6b/jidctint.$(OBJEXT): jpeg-6b/$(am__dirstamp) \
	jpeg-6b/$(DEPDIR)/$(am__dirstamp)
jpeg-6b/jidctred.$(OBJEXT): jpeg-6b/$(am__dirstamp) \
	jpeg-6b/$(DEPDIR)/$(am__dirstamp)
jpeg-6b/jquant1.$(OBJEXT): jpeg-6b/$(am__dirstamp) \
	jpeg-6b/$(DEPDIR)/$(am__dirstamp)
jpeg-6b/jquant2.$(OBJEXT): jpeg-6b/$(am__dirstamp) \
	jpeg-6b/$(DEPDIR)/$(am__dirstamp)
jpeg-6b/jutils.$(OBJEXT): jpeg-6b/$(am__dirstamp) \
	jpeg-6b/$(DEPDIR)/$(am__dirstamp)
jpeg-6b/jmemmgr.$(OBJEXT): jpeg-6b/$(am__dirstamp) \
	jpeg-6b/$(DEPDIR)/$(am__dirstamp)

libjel.a: $(libjel_a_OBJECTS) $(libjel_a_DEPENDENCIES) $(EXTRA_libjel_a_DEPENDENCIES) 
	$(AM_V_at)-rm -f libjel.a
	$(AM_V_AR)$(libjel_a_AR) libjel.a $(libjel_a_OBJECTS) $(libjel_a_LIBADD)
	$(AM_V_at)$(RANLIB) libjel.a

libjpeg.a: $(libjpeg_a_OBJECTS) $(libjpeg_a_DEPENDENCIES) $(EXTRA_libjpeg_a_DEPENDENCIES) 
	$(AM_V_at)-rm -f libjpeg.a
	$(AM_V_AR)$(libjpeg_a_AR) libjpeg.a $(libjpeg_a_OBJECTS) $(libjpeg_a_LIBADD)
	$(AM_V_at)$(RANLIB) libjpeg.a
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(bindir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(bindir)" || exit 1; \
	fi; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p \
	  ; then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' \
	    -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	      echo " $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	      $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' \
	`; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)
utils/$(am__dirstamp):
	@$(MKDIR_P) utils
	@: > utils/$(am__dirstamp)
utils/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) utils/$(DEPDIR)
	@: > utils/$(DEPDIR)/$(am__dirstamp)
utils/jblock.$(OBJEXT): utils/$(am__dirstamp) \
	utils/$(DEPDIR)/$(am__dirstamp)

jblock$(EXEEXT): $(jblock_OBJECTS) $(jblock_DEPENDENCIES) $(EXTRA_jblock_DEPENDENCIES) 
	@rm -f jblock$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(jblock_OBJECTS) $(jblock_LDADD) $(LIBS)
utils/jhist.$(OBJEXT): utils/$(am__dirstamp) \
	utils/$(DEPDIR)/$(am__dirstamp)

jhist$(EXEEXT): $(jhist_OBJECTS) $(jhist_DEPENDENCIES) $(EXTRA_jhist_DEPENDENCIES) 
	@rm -f jhist$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(jhist_OBJECTS) $(jhist_LDADD) $(LIBS)
jpeg-6b/jpegtran.$(OBJEXT): jpeg-6b/$(am__dirstamp) \
	jpeg-6b/$(DEPDIR)/$(am__dirstamp)
jpeg-6b/transupp.$(OBJEXT): jpeg-6b/$(am__dirstamp) \
	jpeg-6b/$(DEPDIR)/$(am__dirstamp)
jpeg-6b/cdjpeg.$(OBJEXT): jpeg-6b/$(am__dirstamp) \
	jpeg-6b/$(DEPDIR)/$(am__dirstamp)
jpeg-6b/rdswitch.$(OBJEXT): jpeg-6b/$(am__dirstamp) \
	jpeg-6b/$(DEPDIR)/$(am__dirstamp)

jpegtran$(EXEEXT): $(jpegtran_OBJECTS) $(jpegtran_DEPENDENCIES) $(EXTRA_jpegtran_DEPENDENCIES) 
	@rm -f jpegtran$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(jpegtran_OBJECTS) $(jpegtran_LDADD) $(LIBS)
utils/jquant.$(OBJEXT): utils/$(am__dirstamp) \
	utils/$(DEPDIR)/$(am__dirstamp)

jquant$(EXEEXT): $(jquant_OBJECTS) $(jquant_DEPENDENCIES) $(EXTRA_jquant_DEPENDENCIES) 
	@rm -f jquant$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(jquant_OBJECTS) $(jquant_LDADD) $(LIBS)
utils/unwedge.$(OBJEXT): utils/$(am__dirstamp) \
	utils/$(DEPDIR)/$(am__dirstamp)

unwedge$(EXEEXT): $(unwedge_OBJECTS) $(unwedge_DEPENDENCIES) $(EXTRA_unwedge_DEPENDENCIES) 
	@rm -f unwedge$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(unwedge_OBJECTS) $(unwedge_LDADD) $(LIBS)
utils/wcap.$(OBJEXT): utils/$(am__dirstamp) \
	utils/$(DEPDIR)/$(am__dirstamp)

wcap$(EXEEXT): $(wcap_OBJECTS) $(wcap_DEPENDENCIES) $(EXTRA_wcap_DEPENDENCIES) 
	@rm -f wcap$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(wcap_OBJECTS) $(wcap_LDADD) $(LIBS)
utils/wedge.$(OBJEXT): utils/$(am__dirstamp) \
	utils/$(DEPDIR)/$(am__dirstamp)

wedge$(EXEEXT): $(wedge_OBJECTS) $(wedge_DEPENDENCIES) $(EXTRA_wedge_DEPENDENCIES) 
	@rm -f wedge$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(wedge_OBJECTS) $(wedge_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)
	-rm -f jpeg-6b/*.$(OBJEXT)
	-rm -f libjel/*.$(OBJEXT)
	-rm -f rscode/*.$(OBJEXT)
	-rm -f utils/*.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include jpeg-6b/$(DEPDIR)/cdjpeg.Po
include jpeg-6b/$(DEPDIR)/jcapimin.Po
include jpeg-6b/$(DEPDIR)/jcapistd.Po
include jpeg-6b/$(DEPDIR)/jccoefct.Po
include jpeg-6b/$(DEPDIR)/jccolor.Po
include jpeg-6b/$(DEPDIR)/jcdctmgr.Po
include jpeg-6b/$(DEPDIR)/jchuff.Po
include jpeg-6b/$(DEPDIR)/jcinit.Po
include jpeg-6b/$(DEPDIR)/jcmainct.Po
include jpeg-6b/$(DEPDIR)/jcmarker.Po
include jpeg-6b/$(DEPDIR)/jcmaster.Po
include jpeg-6b/$(DEPDIR)/jcomapi.Po
include jpeg-6b/$(DEPDIR)/jcparam.Po
include jpeg-6b/$(DEPDIR)/jcphuff.Po
include jpeg-6b/$(DEPDIR)/jcprepct.Po
include jpeg-6b/$(DEPDIR)/jcsample.Po
include jpeg-6b/$(DEPDIR)/jctrans.Po
include jpeg-6b/$(DEPDIR)/jdapimin.Po
include jpeg-6b/$(DEPDIR)/jdapistd.Po
include jpeg-6b/$(DEPDIR)/jdatadst.Po
include jpeg-6b/$(DEPDIR)/jdatasrc.Po
include jpeg-6b/$(DEPDIR)/jdcoefct.Po
include jpeg-6b/$(DEPDIR)/jdcolor.Po
include jpeg-6b/$(DEPDIR)/jddctmgr.Po
include jpeg-6b/$(DEPDIR)/jdhuff.Po
include jpeg-6b/$(DEPDIR)/jdinput.Po
include jpeg-6b/$(DEPDIR)/jdmainct.Po
include jpeg-6b/$(DEPDIR)/jdmarker.Po
include jpeg-6b/$(DEPDIR)/jdmaster.Po
include jpeg-6b/$(DEPDIR)/jdmerge.Po
include jpeg-6b/$(DEPDIR)/jdphuff.Po
include jpeg-6b/$(DEPDIR)/jdpostct.Po
include jpeg-6b/$(DEPDIR)/jdsample.Po
include jpeg-6b/$(DEPDIR)/jdtrans.Po
include jpeg-6b/$(DEPDIR)/jerror.Po
include jpeg-6b/$(DEPDIR)/jfdctflt.Po
include jpeg-6b/$(DEPDIR)/jfdctfst.Po
include jpeg-6b/$(DEPDIR)/jfdctint.Po
include jpeg-6b/$(DEPDIR)/jidctflt.Po
include jpeg-6b/$(DEPDIR)/jidctfst.Po
include jpeg-6b/$(DEPDIR)/jidctint.Po
include jpeg-6b/$(DEPDIR)/jidctred.Po
include jpeg-6b/$(DEPDIR)/jmemansi.Po
include jpeg-6b/$(DEPDIR)/jmemmgr.Po
include jpeg-6b/$(DEPDIR)/jpegtran.Po
include jpeg-6b/$(DEPDIR)/jquant1.Po
include jpeg-6b/$(DEPDIR)/jquant2.Po
include jpeg-6b/$(DEPDIR)/jutils.Po
include jpeg-6b/$(DEPDIR)/rdswitch.Po
include jpeg-6b/$(DEPDIR)/transupp.Po
include libjel/$(DEPDIR)/ijel-ecc.Po
include libjel/$(DEPDIR)/ijel.Po
include libjel/$(DEPDIR)/jel.Po
include libjel/$(DEPDIR)/jpeg-fd-dst.Po
include libjel/$(DEPDIR)/jpeg-fd-src.Po
include libjel/$(DEPDIR)/jpeg-mem-dst.Po
include libjel/$(DEPDIR)/jpeg-mem-src.Po
include rscode/$(DEPDIR)/berlekamp.Po
include rscode/$(DEPDIR)/crcgen.Po
include rscode/$(DEPDIR)/galois.Po
include rscode/$(DEPDIR)/rs.Po
include utils/$(DEPDIR)/jblock.Po
include utils/$(DEPDIR)/jhist.Po
include utils/$(DEPDIR)/jquant.Po
include utils/$(DEPDIR)/unwedge.Po
include utils/$(DEPDIR)/wcap.Po
include utils/$(DEPDIR)/wedge.Po

.c.o:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ $<

.c.obj:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ `$(CYGPATH_W) '$<'` &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ `$(CYGPATH_W) '$<'`
install-pkgconfigDATA: $(pkgconfig_DATA)
	@$(NORMAL_INSTALL)
	@list='$(pkgconfig_DATA)'; test -n "$(pkgconfigdir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(pkgconfigdir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(pkgconfigdir)" || exit 1; \
	fi; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | $(am__base_list) | \
	while read files; do \
	  echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(pkgconfigdir)'"; \
	  $(INSTALL_DATA) $$files "$(DESTDIR)$(pkgconfigdir)" || exit $$?; \
	done

uninstall-pkgconfigDATA:
	@$(NORMAL_UNINSTALL)
	@list='$(pkgconfig_DATA)'; test -n "$(pkgconfigdir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	dir='$(DESTDIR)$(pkgconfigdir)'; $(am__uninstall_files_from_dir)
install-nobase_includeHEADERS: $(nobase_include_HEADERS)
	@$(NORMAL_INSTALL)
	@list='$(nobase_include_HEADERS)'; test -n "$(includedir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(includedir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(includedir)" || exit 1; \
	fi; \
	$(am__nobase_list) | while read dir files; do \
	  xfiles=; for file in $$files; do \
	    if test -f "$$file"; then xfiles="$$xfiles $$file"; \
	    else xfiles="$$xfiles $(srcdir)/$$file"; fi; done; \
	  test -z "$$xfiles" || { \
	    test "x$$dir" = x. || { \
	      echo " $(MKDIR_P) '$(DESTDIR)$(includedir)/$$dir'"; \
	      $(MKDIR_P) "$(DESTDIR)$(includedir)/$$dir"; }; \
	    echo " $(INSTALL_HEADER) $$xfiles '$(DESTDIR)$(includedir)/$$dir'"; \
	    $(INSTALL_HEADER) $$xfiles "$(DESTDIR)$(includedir)/$$dir" || exit $$?; }; \
	done

uninstall-nobase_includeHEADERS:
	@$(NORMAL_UNINSTALL)
	@list='$(nobase_include_HEADERS)'; test -n "$(includedir)" || list=; \
	$(am__nobase_strip_setup); files=`$(am__nobase_strip)`; \
	dir='$(DESTDIR)$(includedir)'; $(am__uninstall_files_from_dir)

ID: $(am__tagged_files)
	$(am__define_uniq_tagged_files); mkid -fID $$unique
tags: tags-am
TAGS: tags

tags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	set x; \
	here=`pwd`; \
	$(am__define_uniq_tagged_files); \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: ctags-am

CTAGS: ctags
ctags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	$(am__define_uniq_tagged_files); \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"
cscope: cscope.files
	test ! -s cscope.files \
	  || $(CSCOPE) -b -q $(AM_CSCOPEFLAGS) $(CSCOPEFLAGS) -i cscope.files $(CSCOPE_ARGS)
clean-cscope:
	-rm -f cscope.files
cscope.files: clean-cscope cscopelist
cscopelist: cscopelist-am

cscopelist-am: $(am__tagged_files)
	list='$(am__tagged_files)'; \
	case "$(srcdir)" in \
	  [\\/]* | ?:[\\/]*) sdir="$(srcdir)" ;; \
	  *) sdir=$(subdir)/$(srcdir) ;; \
	esac; \
	for i in $$list; do \
	  if test -f "$$i"; then \
	    echo "$(subdir)/$$i"; \
	  else \
	    echo "$$sdir/$$i"; \
	  fi; \
	done >> $(top_builddir)/cscope.files

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
	-rm -f cscope.out cscope.in.out cscope.po.out cscope.files

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__post_remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__post_remove_distdir)

dist-lzip: distdir
	tardir=$(distdir) && $(am__tar) | lzip -c $${LZIP_OPT--9} >$(distdir).tar.lz
	$(am__post_remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | XZ_OPT=$${XZ_OPT--e} xz -c >$(distdir).tar.xz
	$(am__post_remove_distdir)

dist-tarZ: distdir
	@echo WARNING: "Support for shar distribution archives is" \
	               "deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__post_remove_distdir)

dist-shar: distdir
	@echo WARNING: "Support for distribution archives compressed with" \
		       "legacy program 'compress' is deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__post_remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__post_remove_distdir)

dist dist-all:
	$(MAKE) $(AM_MAKEFLAGS) $(DIST_TARGETS) am__post_remove_distdir='@:'
	$(am__post_remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lz*) \
	  lzip -dc $(distdir).tar.lz | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir)
	chmod u+w $(distdir)
	mkdir $(distdir)/_build $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build \
	  && ../configure \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	    --srcdir=.. --prefix="$$dc_install_base" \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__post_remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@test -n '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: trying to run $@ with an empty' \
	       '$$(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	$(am__cd) '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	test `$(am__distuninstallcheck_listfiles) | wc -l` -eq 0 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-am
all-am: Makefile $(LIBRARIES) $(PROGRAMS) $(DATA) $(HEADERS)
installdirs:
	for dir in "$(DESTDIR)$(jeldir)" "$(DESTDIR)$(bindir)" "$(DESTDIR)$(pkgconfigdir)" "$(DESTDIR)$(includedir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)
	-rm -f jpeg-6b/$(DEPDIR)/$(am__dirstamp)
	-rm -f jpeg-6b/$(am__dirstamp)
	-rm -f libjel/$(DEPDIR)/$(am__dirstamp)
	-rm -f libjel/$(am__dirstamp)
	-rm -f rscode/$(DEPDIR)/$(am__dirstamp)
	-rm -f rscode/$(am__dirstamp)
	-rm -f utils/$(DEPDIR)/$(am__dirstamp)
	-rm -f utils/$(am__dirstamp)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic clean-jelLIBRARIES \
	clean-noinstLIBRARIES mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf jpeg-6b/$(DEPDIR) libjel/$(DEPDIR) rscode/$(DEPDIR) utils/$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am: install-jelLIBRARIES install-nobase_includeHEADERS \
	install-pkgconfigDATA

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-binPROGRAMS

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf jpeg-6b/$(DEPDIR) libjel/$(DEPDIR) rscode/$(DEPDIR) utils/$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-binPROGRAMS uninstall-jelLIBRARIES \
	uninstall-nobase_includeHEADERS uninstall-pkgconfigDATA

.MAKE: install-am install-strip

.PHONY: CTAGS GTAGS TAGS all all-am am--refresh check check-am clean \
	clean-binPROGRAMS clean-cscope clean-generic \
	clean-jelLIBRARIES clean-noinstLIBRARIES cscope cscopelist-am \
	ctags ctags-am dist dist-all dist-bzip2 dist-gzip dist-lzip \
	dist-shar dist-tarZ dist-xz dist-zip distcheck distclean \
	distclean-compile distclean-generic distclean-tags \
	distcleancheck distdir distuninstallcheck dvi dvi-am html \
	html-am info info-am install install-am install-binPROGRAMS \
	install-data install-data-am install-dvi install-dvi-am \
	install-exec install-exec-am install-html install-html-am \
	install-info install-info-am install-jelLIBRARIES install-man \
	install-nobase_includeHEADERS install-pdf install-pdf-am \
	install-pkgconfigDATA install-ps install-ps-am install-strip \
	installcheck installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic pdf pdf-am ps ps-am tags tags-am uninstall \
	uninstall-am uninstall-binPROGRAMS uninstall-jelLIBRARIES \
	uninstall-nobase_includeHEADERS uninstall-pkgconfigDATA


# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
