from distutils.core import setup, Extension
setup(name='pyjel',
      version='1.0',
      ext_modules=[Extension('pyjel', ['pyjel.c',
	                               'rscode/rs.c',
	                               'rscode/galois.c',
	                               'rscode/berlekamp.c',
	                               'rscode/crcgen.c',
	                               'libjel/ijel-ecc.c',
	                               'libjel/ijel.c',
	                               'libjel/jpeg-mem-dst.c',
	                               'libjel/jpeg-mem-src.c',
	                               'libjel/jpeg-stdio-dst.c',
	                               'libjel/jpeg-stdio-src.c',
	                               'libjel/jel.c'],
                             define_macros=[('JEL_VERSION', '"1.0"'),
                                            ('ECC', '1')],
                             include_dirs=['./include', './rscode', './libjel'],
                             libraries=['jpeg'])],
)
